package com.mycompany.gestiondegranjaslime;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author misae
 */
public class GestionSlimes extends javax.swing.JFrame {
    
    /**
     * Creates new form GestionSlimes
     */
    public GestionSlimes() {
        initComponents();
    }
    //creamos un modelo para poder mostrar nuestros datos en el jlist
    
    //array bidimensonal para guardar datos 
        String Slimes[][] = new String [100][5];
        int SlimeID = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dieta = new javax.swing.JTextField();
        comidaFavorita = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mostrarTodos = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        tipo = new javax.swing.JTextField();
        plort = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        codigoBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSlime = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 82, 61));
        jLabel1.setText("Gestion Slimes");

        jLabel2.setForeground(new java.awt.Color(133, 111, 83));
        jLabel2.setText("Slimes de \"slime rancher\" no \"slimes\" de esos q se apretan");

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 111, 83));
        jLabel3.setText("Ingrese los datos del slime a archivar:");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 111, 83));
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(133, 111, 83));
        jLabel5.setText("Dieta:");

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(133, 111, 83));
        jLabel6.setText("Comida Favorita:");

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(133, 111, 83));
        jLabel7.setText("Plort:");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(133, 111, 83));
        jLabel8.setText("Codigo:");

        dieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietaActionPerformed(evt);
            }
        });

        comidaFavorita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidaFavoritaActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(133, 111, 83));
        guardar.setText("GuArdar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        buscar.setForeground(new java.awt.Color(133, 111, 83));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(133, 111, 83));
        jLabel9.setText("Ingrese el codigo de un slime a buscar:");

        jLabel10.setText("O");

        mostrarTodos.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        mostrarTodos.setForeground(new java.awt.Color(133, 111, 83));
        mostrarTodos.setText("Mostrar Todos");
        mostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(133, 111, 83));
        eliminar.setText("Eliminar Actual");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        plort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plortActionPerformed(evt);
            }
        });

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        codigoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBuscarActionPerformed(evt);
            }
        });

        listaSlime.setColumns(20);
        listaSlime.setRows(5);
        jScrollPane2.setViewportView(listaSlime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dieta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plort, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comidaFavorita, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(guardar)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addComponent(mostrarTodos))
                            .addComponent(eliminar)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37))
                            .addComponent(jLabel2))
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comidaFavorita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(plort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(codigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buscar)
                                .addComponent(jLabel10)
                                .addComponent(mostrarTodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(guardar))
                    .addComponent(eliminar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietaActionPerformed

    private void comidaFavoritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidaFavoritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comidaFavoritaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
//logica del boton guardar
        //obtenemos todos los datos que queremos guardar de los campos
        String Tipo = tipo.getText();
        String Dieta = dieta.getText();
        String ComidaFav = comidaFavorita.getText();
        String Plort = plort.getText();
        String Codigo = codigo.getText();
        //una vez traemos lo que vamos a usar, verificamos si esta vacio
        if(Tipo.isEmpty() || Dieta.isEmpty() ||ComidaFav.isEmpty() ||Plort.isEmpty() ||Codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete los campos bien no sea burro", "ERROororoRORO:", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //verifica que el ID colocado NO exista antes de guardarlo
        for(int i=0;i<SlimeID;i++){
         if(Codigo.equals(Slimes[i][4])){
        //si ya existe arroja un error sin limpiando SOLO el campo del ID para que sea mas facil volver a poner otro
           JOptionPane.showMessageDialog(this, "ESE ID YA EXISTE, ponga otro ;)", "ERROR FATAL:", JOptionPane.ERROR_MESSAGE);
           codigo.setText("");
           return;
        }   
}
        //si no existe guardamos normal
        //guardamos los datos colocandolos en nuestro array bidimensional ubicandolos con su ID como fila y en 5 columnas distintas
        Slimes[SlimeID][0] = Tipo;
        Slimes[SlimeID][1] = Dieta;
        Slimes[SlimeID][2] = ComidaFav;
        Slimes[SlimeID][3] = Plort;
        Slimes[SlimeID][4] = Codigo;
        //mensaje de alerta que avise que se guardo bien (aunque siempre sale aun si no se guardo bien)
        JOptionPane.showMessageDialog(this, "Registro Guardado Existosamente!");
        //aumentamos el id en 1 para que la siguiente carga lo haga en la siguiente fila
        SlimeID++;
        //colocamos todo en blanco para hacer mas facil la siguiente carga
        tipo.setText("");
         dieta.setText("");
          comidaFavorita.setText(""); 
           plort.setText("");
            codigo.setText("");
       
    }//GEN-LAST:event_guardarActionPerformed
        
    private void mostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosActionPerformed
    // limpiar campos y text area
listaSlime.setText("");
codigoBuscar.setText("");

// recorrer todas las filas hasta SlimeID para verificar si es null
for (int m = 0; m < SlimeID; m++) {
    boolean filaVacia = true;
    
    // verificar si la fila COMPLETA es null 
    for (int n = 0; n < 4; n++) {
        if (Slimes[m][n] != null) {
            filaVacia = false;
            break;
        }
    }
    
    // Si la fila no es null se muestra
    if (!filaVacia) {
        listaSlime.append("\n");
        for (int n = 0; n < 4; n++) {
            if (Slimes[m][n] != null) {
                listaSlime.append(n + 1 + "- " + Slimes[m][n] + "\n");
            }
        }
    }
}
    
    }//GEN-LAST:event_mostrarTodosActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void plortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plortActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void codigoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBuscarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
    //logica del boton buscar
    int Encontrado = 0;
    String buscador = codigoBuscar.getText();
    listaSlime.setText("");
    /*
    El bucle itera sobre el ID de los registros para alcanzar el total de estos, toma la variable "buscador"
    para compararlo por cada iteracion para ver si coincide con un codigo en los registros, si es asi
    lo agrega al TextArea con un append para mostrarlo
    */
    for(int n =0;n<SlimeID;n++){
        if(buscador.equals(Slimes[n][4])){
            for(int m =0;m<4;m++){
         listaSlime.append(m+1 + "- " + Slimes[n][m] + "\n");
            }
            //rompe el bucle y coloca la bandera en 1
            Encontrado = 1;
            return;
        }
    }
    //si no se encuentrar coincidencias da un error y limpia el campo
    if(Encontrado == 0){
        JOptionPane.showMessageDialog(this, "No existen registros con ese ID asociado");
        listaSlime.setText("");
    }
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        //logica del btom borrar
        // no se, le borro el id entonces ya no existe jiji 
        String eliminador = codigoBuscar.getText();
        
        for(int n =0;n<SlimeID;n++){
        if(eliminador.equals(Slimes[n][4])){
           Slimes[n][0] = null;
           Slimes[n][1] = null;
           Slimes[n][2] = null;
           Slimes[n][3] = null;
           Slimes[n][4] = null;
           JOptionPane.showMessageDialog(this, "Se elimino el registro de forma exitosa ;)");
           listaSlime.setText("");
           codigoBuscar.setText("");
        }
    }
    
        
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */ // <-- que es esto
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSlimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSlimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSlimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSlimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionSlimes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigoBuscar;
    private javax.swing.JTextField comidaFavorita;
    private javax.swing.JTextField dieta;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea listaSlime;
    private javax.swing.JButton mostrarTodos;
    private javax.swing.JTextField plort;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
